### ISSUE TITLE
Older Version Compatibilities

### ISSUE THREAD

**Issue by loonaticx** [TrevisanGMW/gt-tools#83]
Original issue name: Error: line 1: global name 'ModuleNotFoundError' is not defined

Hi there. When trying to use the newest version of GT tools (v.2.0.0), all of the commands fail to execute with this error:
```
# Error: line 1: global name 'ModuleNotFoundError' is not defined
# Traceback (most recent call last):
#   File "<maya console>", line 1, in <module>
#   File "C:/Users/Loonatic-V/Documents/maya/2019/scripts\gt_tools\__init__.py", line 36, in execute_script
#     except ModuleNotFoundError as e:
# NameError: global name 'ModuleNotFoundError' is not defined # 
```

I have reinstalled GT tools and looked up this error online. I believe this may be caused due to Python version incompatibility. Was GT tools tested on relatively older versions of Maya, more specifically ones that may be using Python 2.7? (My version of Autodesk Maya 2019 uses Python 2.7)

Something I found related to this issue online:
https://stackoverflow.com/a/54153580/15407062

After testing this on my end, it seems like a few other pieces, such as importlib are broken as well:
```
# Error: line 1: 'module' object has no attribute 'reload'
# Traceback (most recent call last):
#   File "<maya console>", line 1, in <module>
#   File "C:/Users/Loonatic-V/Documents/maya/2019/scripts\gt_tools\__init__.py", line 35, in execute_script
#     importlib.reload(module)
# AttributeError: 'module' object has no attribute 'reload' # 
```
Here's a commenter with the same issue with a reply explaining that it's not compatible with 2.7
https://github.com/BitMEX/sample-market-maker/issues/156#issuecomment-421070695

To support older Maya versions that may be using relatively older versions of Python, perhaps there should be a version check in init to determine which modules should be setup to avoid these version differences? I don't know if there's a feasible way to somehow upgrade Maya's python version without upgrading the actual software itself. (I have to work in Maya 2019 in my situation to ensure my files can be compatible for others to work with in my space)

**Comment by thegreenpuppet** [comment]
oh i got the same issue, im using maya 2020.4

**Comment by TrevisanGMW** [comment]
Hey guys, I've been working with Maya 2022 (Python 3) here so I didn't test it much with Python 2. 
Let me fix it here, I'll release an update for it soon 👍

**Comment by TrevisanGMW** [comment]
Hey @loonaticx and @thegreenpuppet,
I've released a new [update ](https://github.com/TrevisanGMW/gt-tools/releases/tag/v2.0.1) with Python 2.7 checks. It should now work with Python 2.7 or 3+
Feel free to re-open the issue in case you're still having issues with it 🚀
